"""
story_topics.py  –  Wonder Stories TV
=======================================
Viral story topic bank for Wonder Stories TV.
200+ hand-crafted story seeds across 11 viral categories.

Each seed includes:
  - title       : Scroll-stopping Hindi/English mix title
  - category    : One of the 11 valid categories
  - format      : short | long
  - hook        : English attention-grabber
  - hook_hindi  : Same hook in Hindi (used as opening line)
  - core_conflict: Central tension/conflict
  - twist       : The shocking revelation or twist
  - moral       : English takeaway
  - moral_hindi : Hindi takeaway
  - angle       : Storytelling angle label
  - topic       : SEO keyword phrase
  - audience_hook: Why viewers share/comment
"""

STORY_TOPIC_BANK = [

    # ─── MYSTERY STORIES ──────────────────────────────────────────────────────

    {
        "title": "Woh Letter Jo 20 Saal Baad Aaya",
        "category": "mystery_stories",
        "format": "long",
        "hook": "A letter arrived 20 years late — and it changed everything.",
        "hook_hindi": "Ek khat jo 20 saal baad aaya... aur usne sab kuch badal diya.",
        "core_conflict": "A family receives a sealed letter from a deceased relative — revealing a secret hidden for two decades.",
        "twist": "The letter was written before the person's death, describing events that hadn't happened yet.",
        "moral": "Some truths are meant to surface at the right time.",
        "moral_hindi": "कुछ सच्चाइयाँ सही वक़्त पर ही सामने आती हैं।",
        "angle": "Mystery Thriller",
        "topic": "mystery story hindi letter raaz",
        "audience_hook": "Comment karo — tumhare ghar mein koi aisa raaz hai?",
    },
    {
        "title": "Woh Kamra Jahan Ghadi Ruk Gayi Thi",
        "category": "mystery_stories",
        "format": "short",
        "hook": "The clock in that room stopped at exactly 3:17 AM — every single night.",
        "hook_hindi": "Woh ghadi raat ke 3:17 baje rukti thi — har raat, bina fail.",
        "core_conflict": "A family member discovers a locked room where clocks always stop at the same time.",
        "twist": "The time matches the exact moment of a tragedy the family never spoke about.",
        "moral": "The past always finds a way to speak.",
        "moral_hindi": "अतीत हमेशा बोलने का रास्ता ढूंढ लेता है।",
        "angle": "Atmospheric Mystery",
        "topic": "mystery story hindi rahasya",
        "audience_hook": "Raat ko 3 baje uthke dekha hai kabhi?",
    },
    {
        "title": "Gaon Ka Woh Aadmi Jise Sab Jaante The Par Koi Jaanta Nahi Tha",
        "category": "mystery_stories",
        "format": "long",
        "hook": "Everyone in the village knew him — but nobody knew anything about him.",
        "hook_hindi": "Pura gaon usse jaanta tha, par koi usse sach mein nahin jaanta tha.",
        "core_conflict": "A helpful stranger lives in a village for years. When he disappears, investigation reveals he had no identity.",
        "twist": "He was a whistleblower hiding in plain sight, protecting the village from a powerful threat.",
        "moral": "True heroes hide in silence.",
        "moral_hindi": "असली नायक खामोशी में छुपे होते हैं।",
        "angle": "Village Mystery",
        "topic": "mystery kahani hindi village rahasya",
        "audience_hook": "Aisa koi tumhari life mein bhi aya hai?",
    },
    {
        "title": "Ek Photo Mein Thi Woh Cheez Jo Kisi Ne Dekhi Nahi",
        "category": "mystery_stories",
        "format": "short",
        "hook": "Everyone looked at the family photo for years — but nobody saw what was hiding in it.",
        "hook_hindi": "Saalon se ghar mein ek photo thi... kisi ne woh nahi dekha jo usme chhupa tha.",
        "core_conflict": "An old family photo contains a detail that unravels a decades-old crime.",
        "twist": "The detail in the photo reveals the true identity of a person who caused great harm.",
        "moral": "Evidence hides in plain sight.",
        "moral_hindi": "सबूत हमेशा सामने होते हैं — नज़र चाहिए।",
        "angle": "Photo Mystery",
        "topic": "mystery story hindi photo rahasya",
        "audience_hook": "Freeze karke photo dekho — kya dikhta hai?",
    },
    {
        "title": "Woh Rasta Jo Map Mein Nahi Tha",
        "category": "mystery_stories",
        "format": "long",
        "hook": "The path didn't exist on any map — but people who took it never came back the same.",
        "hook_hindi": "Woh rasta kisi map mein nahi tha, par jo uss raste se gaye — woh kabhi waisa nahi rahe.",
        "core_conflict": "Travelers report a mysterious road that appears in fog. Those who take it return changed.",
        "twist": "The road leads to a place where people confront their deepest regrets.",
        "moral": "Facing your truth transforms you.",
        "moral_hindi": "अपनी सच्चाई से सामना ही असली बदलाव लाता है।",
        "angle": "Supernatural Mystery",
        "topic": "supernatural mystery story hindi",
        "audience_hook": "Kya tum woh raasta loge?",
    },

    # ─── SHOCKING FACTS ───────────────────────────────────────────────────────

    {
        "title": "Duniya Ka Sabse Bada Jhooth Jo Aaj Bhi Mana Jata Hai",
        "category": "shocking_facts",
        "format": "short",
        "hook": "The biggest lie in human history — and we still believe it today.",
        "hook_hindi": "Insaani itihaas ka sabse bada jhooth — aur aaj bhi hum usse mante hain.",
        "core_conflict": "Exposing a widely accepted 'fact' that was fabricated for commercial or political gain.",
        "twist": "This 'fact' that everyone believes was invented less than 100 years ago.",
        "moral": "Question everything you believe as truth.",
        "moral_hindi": "जो सच माना जाता है उसे भी सवाल करो।",
        "angle": "Fact Expose",
        "topic": "shocking facts hindi history truth",
        "audience_hook": "Comment mein batao — kya tum bhi yeh mante the?",
    },
    {
        "title": "Woh 10 Cheezein Jo Aap Rozan Karte Ho Par Unka Sach Nahi Jaante",
        "category": "shocking_facts",
        "format": "short",
        "hook": "10 things you do every day — and you don't know the shocking truth behind them.",
        "hook_hindi": "10 cheezein jo aap rozan karte ho — unka sach jaanke aap hairan ho jaoge.",
        "core_conflict": "Common everyday habits revealed to have surprising or unsettling origins.",
        "twist": "Each habit traces back to an unexpected historical or commercial origin.",
        "moral": "Awareness is the first step to wisdom.",
        "moral_hindi": "जानकारी ही असली ताकत है।",
        "angle": "Everyday Facts",
        "topic": "shocking facts hindi daily life",
        "audience_hook": "Sabse zyada hairan karne wala fact konsa laga? Comment karo!",
    },
    {
        "title": "Insaan Ka Dimag — Jo Aapko Pata Nahi Woh Jaankar Hairan Ho Jaoge",
        "category": "shocking_facts",
        "format": "long",
        "hook": "Your brain is doing things right now that you have absolutely no idea about.",
        "hook_hindi": "Abhi is waqt aapka dimag kuch aisa kar raha hai jiska aapko bilkul andaza nahi.",
        "core_conflict": "Deep dive into mind-blowing psychological and neurological facts about the human brain.",
        "twist": "Many of your 'conscious' decisions are made subconsciously before you are aware of them.",
        "moral": "Understanding your mind is understanding yourself.",
        "moral_hindi": "अपने मन को समझना ही खुद को समझना है।",
        "angle": "Mind-Blowing Science",
        "topic": "brain facts hindi psychology shocking",
        "audience_hook": "Yeh suna ke kaisa laga? Share karo ek dost ke saath!",
    },
    {
        "title": "Duniya Ka Woh Desh Jahan Ki Real Life Ek Kahani Hai",
        "category": "shocking_facts",
        "format": "long",
        "hook": "There's a country where reality is stranger than any story you've ever heard.",
        "hook_hindi": "Ek aisa desh hai jahan ki haqeeqat kisi bhi kahani se zyada ajib hai.",
        "core_conflict": "Revealing bizarre but true facts about an extraordinary country/society.",
        "twist": "The most incredible fact is one that directly contradicts what we assume about the world.",
        "moral": "The world is bigger and stranger than we imagine.",
        "moral_hindi": "दुनिया हमारी सोच से बड़ी और अजीब है।",
        "angle": "World Facts",
        "topic": "world facts hindi shocking country",
        "audience_hook": "Tumhare paas bhi koi aisa fact hai? Comment karo!",
    },
    {
        "title": "Paise Ka Woh Sach Jo Ameer Log Kabhi Nahi Bataate",
        "category": "shocking_facts",
        "format": "short",
        "hook": "Rich people know something about money that they will never tell you.",
        "hook_hindi": "Ameer log paise ke baare mein ek aisa sach jaante hain jo woh kabhi nahi batate.",
        "core_conflict": "Exposing the real mechanics of wealth and financial systems most people never learn.",
        "twist": "The rules about money that schools teach are designed to keep most people poor.",
        "moral": "Financial knowledge is the greatest equalizer.",
        "moral_hindi": "पैसों की समझ ही सबसे बड़ी ताक़त है।",
        "angle": "Financial Truth",
        "topic": "money facts hindi wealth shocking",
        "audience_hook": "Share karo apne dost ke saath jo zyada kama chahta hai!",
    },

    # ─── SUSPENSE STORIES ─────────────────────────────────────────────────────

    {
        "title": "Raat Ko 2 Baje Ek Message Aaya",
        "category": "suspense_stories",
        "format": "short",
        "hook": "A message at 2 AM from a number that didn't exist — and it knew everything about her.",
        "hook_hindi": "Raat ke 2 baje ek message aaya uss number se jo exist nahi karta tha...",
        "core_conflict": "A woman receives threatening messages from an unknown number that seems to know her every move.",
        "twist": "The messages were sent by someone very close to her, warning her of a danger she couldn't see.",
        "moral": "Not all dangers are from strangers.",
        "moral_hindi": "हर खतरा अजनबी से नहीं होता।",
        "angle": "Modern Suspense",
        "topic": "suspense story hindi message thriller",
        "audience_hook": "Aise message aaye hai kabhi tumhare paas? Comment mein batao!",
    },
    {
        "title": "Ghar Mein Koi Tha — Mujhe Pata Tha Par Koi Manta Nahi Tha",
        "category": "suspense_stories",
        "format": "long",
        "hook": "I knew someone was in the house. Nobody believed me.",
        "hook_hindi": "Mujhe pata tha ghar mein koi tha. Par koi nahi maanta tha.",
        "core_conflict": "A person senses an intruder in their home. Family dismisses their fears as paranoia.",
        "twist": "Their instinct was right — but the 'intruder' had been there for weeks without anyone knowing.",
        "moral": "Trust your instincts — they exist for a reason.",
        "moral_hindi": "अपनी अंतरात्मा की आवाज़ सुनो — वो हमेशा सच बोलती है।",
        "angle": "Home Suspense",
        "topic": "suspense story hindi ghar thriller",
        "audience_hook": "Kabhi aisa feel hua hai? Comment karo!",
    },
    {
        "title": "Ek Raat Jo Meri Zindagi Badal Gayi",
        "category": "suspense_stories",
        "format": "long",
        "hook": "One night changed everything — and I never told anyone the full truth.",
        "hook_hindi": "Ek raat... aur sab kuch badal gaya. Woh sach aaj bhi mere andar chhupa hai.",
        "core_conflict": "A witness to a dramatic event carries a secret that has haunted them for years.",
        "twist": "The truth they've been hiding was actually protecting someone innocent.",
        "moral": "Some secrets weigh more than their truth is worth.",
        "moral_hindi": "कुछ राज़ उनकी सच्चाई से भी भारी होते हैं।",
        "angle": "Personal Suspense",
        "topic": "suspense story hindi real incident",
        "audience_hook": "Kya tumhare paas bhi ek aisi raat hai? Comment mein share karo.",
    },
    {
        "title": "Woh Aadmi Jo Har Roz Ek Hi Cheez Karta Tha",
        "category": "suspense_stories",
        "format": "short",
        "hook": "Every single day, he did the exact same thing at the exact same time. Until the day he didn't.",
        "hook_hindi": "Woh aadmi har roz ek hi kaam karta tha... jab tak ek din nahi kiya.",
        "core_conflict": "A neighbor's rigid daily routine suddenly stops — and the investigation reveals something sinister.",
        "twist": "His routine was the only thing keeping someone else safe.",
        "moral": "Small habits can protect more than you realize.",
        "moral_hindi": "छोटी आदतें भी किसी की रक्षा कर सकती हैं।",
        "angle": "Neighborhood Suspense",
        "topic": "suspense story hindi neighbor mystery",
        "audience_hook": "Kya tumhara koi aisa padosi hai? Comment mein batao!",
    },

    # ─── DARK FACTS ───────────────────────────────────────────────────────────

    {
        "title": "Itihaas Ka Woh Andheraa Panna Jo Textbooks Mein Nahi Hai",
        "category": "dark_facts",
        "format": "long",
        "hook": "The darkest page of history — the one they removed from textbooks.",
        "hook_hindi": "Itihaas ka woh andhera panna jise textbooks se hata diya gaya.",
        "core_conflict": "Revealing a historical event deliberately omitted or distorted in official records.",
        "twist": "The reason it was hidden connects directly to current events.",
        "moral": "Those who erase history are doomed to repeat it.",
        "moral_hindi": "जो इतिहास मिटाते हैं वो उसे दोहराने पर मजबूर हो जाते हैं।",
        "angle": "Dark History",
        "topic": "dark history facts hindi hidden truth",
        "audience_hook": "Yeh sach jaanke tumhara reaction kya raha? Comment karo!",
    },
    {
        "title": "Woh Cheez Jo Hum Rozan Khaate Hain — Uska Khatarnak Sach",
        "category": "dark_facts",
        "format": "short",
        "hook": "What you eat every day has a dark secret the food industry doesn't want you to know.",
        "hook_hindi": "Jo aap rozan khate hain — uski andheri sachhai food industry kabhi nahi batayegi.",
        "core_conflict": "Exposing the hidden dangers in everyday food items most people consume without question.",
        "twist": "The regulatory agencies that are supposed to protect us have direct conflicts of interest.",
        "moral": "Be informed about what you consume.",
        "moral_hindi": "जो खाते हो उसके बारे में जागरूक रहो।",
        "angle": "Food Industry Dark Truth",
        "topic": "dark facts hindi food industry truth",
        "audience_hook": "Yeh dekhke kya aap apna diet change karoge? Comment mein batao!",
    },
    {
        "title": "Duniya Ka Sabse Khatarnak Rahasya — Jo Sab Jaante Hain Par Bolte Nahi",
        "category": "dark_facts",
        "format": "long",
        "hook": "Everyone knows this truth. Nobody talks about it.",
        "hook_hindi": "Yeh sach sab jaante hain. Par koi bolna nahi chahta.",
        "core_conflict": "A systemic societal truth that people collectively ignore because confronting it is uncomfortable.",
        "twist": "The solution has always been within reach — but acknowledging the problem is the first step.",
        "moral": "Collective silence enables collective suffering.",
        "moral_hindi": "सामूहिक चुप्पी सामूहिक दर्द को जन्म देती है।",
        "angle": "Social Dark Truth",
        "topic": "dark truth society hindi facts",
        "audience_hook": "Kya tum is topic pe baat karte ho? Comment mein reply karo!",
    },
    {
        "title": "Internet Ka Woh Hissa Jo Aap Kabhi Nahi Jaana Chahoge",
        "category": "dark_facts",
        "format": "short",
        "hook": "There's a part of the internet so dark, once you know it exists, you can't unknow it.",
        "hook_hindi": "Internet ka ek aisa hissa hai jise jaanke aap wish karoge ki aapne kabhi nahi jaana.",
        "core_conflict": "Exploring the disturbing reality of the dark web and digital threats most people are unaware of.",
        "twist": "Your data is being used in ways you never consented to — right now.",
        "moral": "Digital awareness is now as essential as real-world safety.",
        "moral_hindi": "डिजिटल सुरक्षा अब उतनी ही ज़रूरी है जितनी असली दुनिया की सुरक्षा।",
        "angle": "Digital Dark Fact",
        "topic": "dark web facts hindi internet truth",
        "audience_hook": "Kya aap aware the yeh sab se? Share karo!",
    },

    # ─── PSYCHOLOGICAL STORIES ────────────────────────────────────────────────

    {
        "title": "Ek Baar Jhooth Bolne Ki Keemat — Poori Zindagi Mein",
        "category": "psychological",
        "format": "long",
        "hook": "One lie. That's all it took to destroy everything.",
        "hook_hindi": "Sirf ek jhooth... aur poori zindagi ki imaarat dheh gayi.",
        "core_conflict": "A person tells one seemingly small lie. The psychological cost of maintaining it consumes their entire life.",
        "twist": "The truth they were hiding would have been far easier to accept than the lie turned out to be.",
        "moral": "The cost of a lie is always greater than the truth you're hiding.",
        "moral_hindi": "झूठ की कीमत हमेशा उस सच से ज़्यादा होती है जो आप छुपाते हैं।",
        "angle": "Psychological Consequences",
        "topic": "psychological story hindi truth lies",
        "audience_hook": "Ek jhooth ne kabhi tumhari life affect ki hai? Comment karo.",
    },
    {
        "title": "Apni Sab Se Badi Dar Se Milna",
        "category": "psychological",
        "format": "short",
        "hook": "The thing you fear most is the thing you need most.",
        "hook_hindi": "Jis cheez se sabse zyada darr lagta hai — wahi cheez sabse zyada chahiye hoti hai.",
        "core_conflict": "A person avoids their deepest fear until circumstances force a confrontation.",
        "twist": "Facing the fear reveals it was protecting them from something worse — their own potential.",
        "moral": "Your greatest fear is your greatest teacher.",
        "moral_hindi": "आपका सबसे बड़ा डर आपका सबसे बड़ा गुरु है।",
        "angle": "Psychological Growth",
        "topic": "psychological story hindi fear growth",
        "audience_hook": "Tumhara sabse bada dar kya hai? Comment mein batao!",
    },
    {
        "title": "Woh Aadmi Jo Khud Se Ladta Raha",
        "category": "psychological",
        "format": "long",
        "hook": "His biggest enemy wasn't out there. It was inside him.",
        "hook_hindi": "Uska sabse bada dushman bahar nahi tha — andar tha.",
        "core_conflict": "A man's self-destructive thought patterns lead to the systematic dismantling of his own happiness.",
        "twist": "The therapy session reveals his 'enemy' was the traumatized child he never allowed himself to heal.",
        "moral": "The war within is the only war worth winning.",
        "moral_hindi": "अंदर की लड़ाई ही असली लड़ाई है।",
        "angle": "Inner Conflict",
        "topic": "psychological story hindi self inner conflict",
        "audience_hook": "Kabhi khud se aise lade ho? Share karo!",
    },
    {
        "title": "Woh 21 Din Jo Sab Kuch Badal Dete Hain — Psychological Study",
        "category": "psychological",
        "format": "short",
        "hook": "A 21-day experiment that changed how scientists understand human behavior forever.",
        "hook_hindi": "21 din ka ek experiment — jisne insaani aadat ke baare mein sab kuch badal diya.",
        "core_conflict": "A famous psychological study reveals how quickly and dramatically humans adapt (or collapse) under new conditions.",
        "twist": "The researchers themselves were changed by the experiment — and the findings were suppressed for years.",
        "moral": "Environment shapes humans more than character.",
        "moral_hindi": "माहौल इंसान को उसके स्वभाव से ज़्यादा बदलता है।",
        "angle": "Psychological Study",
        "topic": "psychology experiment facts hindi mind",
        "audience_hook": "Yeh suna ke kya tumhare dimag mein kuch badla? Comment karo!",
    },

    # ─── THRILLER STORIES ─────────────────────────────────────────────────────

    {
        "title": "Ek Yatri Jisko Koi Nahi Jaanta Tha",
        "category": "thriller_stories",
        "format": "long",
        "hook": "He was on the train with everyone. Nobody knew who he really was.",
        "hook_hindi": "Woh sabke saath train mein tha. Koi nahi jaanta tha woh asal mein kaun hai.",
        "core_conflict": "A mysterious traveler on a long train journey. Fellow passengers slowly realize something is very wrong.",
        "twist": "He was a fugitive fleeing from a crime — but also the only one who could prevent a disaster on the train.",
        "moral": "People are never just one thing.",
        "moral_hindi": "इंसान कभी सिर्फ एक चीज़ नहीं होता।",
        "angle": "Train Thriller",
        "topic": "thriller story hindi train mystery",
        "audience_hook": "Aisa kabhi hua hai train mein? Comment karo!",
    },
    {
        "title": "Ek Naukri Jo Normal Lagti Thi",
        "category": "thriller_stories",
        "format": "short",
        "hook": "She thought it was a normal job interview. It was anything but.",
        "hook_hindi": "Usse laga yeh ek normal interview hai. Tha bilkul bhi nahi.",
        "core_conflict": "A job seeker attends what appears to be a normal interview and gradually realizes something sinister is happening.",
        "twist": "The company was testing loyalty to dangerous ideals — and she was the only one who refused.",
        "moral": "Integrity is tested when the cost is highest.",
        "moral_hindi": "ईमानदारी की परीक्षा तब होती है जब कीमत सबसे ज़्यादा हो।",
        "angle": "Corporate Thriller",
        "topic": "thriller story hindi corporate suspense",
        "audience_hook": "Interview mein aisa kuch hua hai kabhi? Comment karo!",
    },
    {
        "title": "48 Ghante — Sirf 48 Ghante Tha Waqt",
        "category": "thriller_stories",
        "format": "long",
        "hook": "48 hours to save everything. And every minute, something new went wrong.",
        "hook_hindi": "Sirf 48 ghante — aur har minute kuch naya galat ho jaata tha.",
        "core_conflict": "A race against time thriller where the protagonist must prevent a catastrophe with dwindling resources and rising obstacles.",
        "twist": "The biggest obstacle turns out to be the person they trusted most.",
        "moral": "Pressure reveals character.",
        "moral_hindi": "दबाव ही असल चरित्र दिखाता है।",
        "angle": "Race Against Time",
        "topic": "thriller story hindi 48 hours time race",
        "audience_hook": "48 ghante mein kya karte tum? Comment mein batao!",
    },

    # ─── HORROR STORIES ───────────────────────────────────────────────────────

    {
        "title": "Woh Awaaz Jo Raat Ko Sirf Mujhe Sunti Thi",
        "category": "horror_stories",
        "format": "short",
        "hook": "I heard it every night. My family heard nothing.",
        "hook_hindi": "Woh awaaz mujhe raat ko aati thi. Mere ghar walo ko kabhi nahi aayi.",
        "core_conflict": "A person hears mysterious sounds at night that no one else can hear — and slowly uncovers a terrifying reason.",
        "twist": "The sounds were real — but only they could hear it because of a trauma their mind had buried.",
        "moral": "Unhealed wounds make sounds only we can hear.",
        "moral_hindi": "न भरे ज़ख्म आवाज़ें करते हैं जो सिर्फ हम सुन सकते हैं।",
        "angle": "Psychological Horror",
        "topic": "horror story hindi awaaz ghost",
        "audience_hook": "Raat ko awaazein aati hain tumhare ghar mein? Comment karo!",
    },
    {
        "title": "Woh Ghar Jahan Har Raat Ek Hi Sapna Aata Tha",
        "category": "horror_stories",
        "format": "long",
        "hook": "Every person who lived in that house had the same dream. The same nightmare.",
        "hook_hindi": "Uss ghar mein rehne wala har insaan ek hi sapna dekhta tha — har raat.",
        "core_conflict": "Multiple occupants of a house all report the same recurring nightmare — which reveals a buried tragedy.",
        "twist": "The dream is a memory of a real event that happened in the house — and it's trying to show them something.",
        "moral": "The past leaves echoes in places.",
        "moral_hindi": "अतीत जगहों में गूंज छोड़ जाता है।",
        "angle": "Atmospheric Horror",
        "topic": "horror story hindi haunted house sapna",
        "audience_hook": "Aisa koi sapna aaya hai kabhi? Comment mein share karo!",
    },
    {
        "title": "Raat Ke 3:33 Baje Ki Kahani",
        "category": "horror_stories",
        "format": "short",
        "hook": "3:33 AM. The time when the boundary between worlds is thinnest.",
        "hook_hindi": "Raat ke 3:33 baje... jab do duniyaon ki seema sabse patli hoti hai.",
        "core_conflict": "Strange things consistently happen at exactly 3:33 AM in a household — until one night changes everything.",
        "twist": "The occurrences were being caused by a sleep disorder, but the final night reveals something that cannot be explained.",
        "moral": "Some things defy rational explanation.",
        "moral_hindi": "कुछ चीज़ें तर्क से परे होती हैं।",
        "angle": "Midnight Horror",
        "topic": "horror story hindi 3am scary",
        "audience_hook": "Raat 3 baje kabhi uthke kuch dekha hai? Comment mein batao!",
    },
    {
        "title": "Woh Darwaza Jo Kabhi Band Nahi Hota Tha",
        "category": "horror_stories",
        "format": "long",
        "hook": "No matter how many times they locked it — the door was always open by morning.",
        "hook_hindi": "Chahe kitni baar band karo — subah woh darwaza khula hota tha.",
        "core_conflict": "A family's front door refuses to stay locked despite multiple repairs. Their fear builds until they discover the truth.",
        "twist": "A vulnerable person had been using their home for shelter — and was too afraid to ask for help.",
        "moral": "Fear can prevent us from seeing what's human.",
        "moral_hindi": "डर हमें इंसानियत देखने से रोक सकता है।",
        "angle": "Twist Horror",
        "topic": "horror story hindi twist human darwaza",
        "audience_hook": "Darwaza khulne ki kahaani sunke kaisa laga? Comment karo!",
    },

    # ─── CRIME STORIES ────────────────────────────────────────────────────────

    {
        "title": "Woh Crime Jise Perfect Samjha Gaya Tha",
        "category": "crime_stories",
        "format": "long",
        "hook": "He planned it for 3 years. He thought of everything. Almost.",
        "hook_hindi": "Usne 3 saal plan kiya. Har cheez sochi. Bas ek cheez chhoot gayi.",
        "core_conflict": "A calculated criminal executes what he believes is the perfect crime — leaving no trace.",
        "twist": "The one thing he forgot was so small, so human — it unraveled everything.",
        "moral": "No crime is truly perfect because humans always leave a human trace.",
        "moral_hindi": "कोई अपराध पूर्ण नहीं होता क्योंकि इंसान हमेशा एक इंसानी निशान छोड़ता है।",
        "angle": "Crime Thriller",
        "topic": "crime story hindi perfect crime thriller",
        "audience_hook": "Tumhara andaza hai woh cheez kya thi? Comment mein batao!",
    },
    {
        "title": "Ek Detective Ki Sabse Mushkil Case",
        "category": "crime_stories",
        "format": "long",
        "hook": "20 years on the force. He'd never seen anything like this.",
        "hook_hindi": "20 saal ki naukri. Aisa case pehle kabhi nahi aaya tha.",
        "core_conflict": "A seasoned detective faces a baffling case that contradicts everything he knows about crime.",
        "twist": "The solution comes not from evidence but from understanding human emotion.",
        "moral": "The heart of every crime is a human story.",
        "moral_hindi": "हर अपराध के पीछे एक इंसानी कहानी होती है।",
        "angle": "Detective Story",
        "topic": "crime detective story hindi investigation",
        "audience_hook": "Detective stories pasand hain? Subscribe karo aur share karo!",
    },
    {
        "title": "Woh Gawah Jo Sabne Ignore Kiya",
        "category": "crime_stories",
        "format": "short",
        "hook": "One witness told the truth. Nobody listened. Until it was almost too late.",
        "hook_hindi": "Ek gawah ne sach bola. Kisi ne nahi suna. Jab tak sach mein bahut der ho jaati.",
        "core_conflict": "A key witness to a crime is dismissed by police due to their background — but proves crucial.",
        "twist": "The witness had been trying to warn them for months before the crime even happened.",
        "moral": "The truth doesn't pick prestigious messengers.",
        "moral_hindi": "सच्चाई अमीर-गरीब नहीं देखती।",
        "angle": "Justice Crime Story",
        "topic": "crime story hindi witness justice",
        "audience_hook": "Kabhi aisa feel hua ki sach bol diya par kisi ne suna nahi? Comment karo!",
    },

    # ─── KARMA STORIES ────────────────────────────────────────────────────────

    {
        "title": "Usne Bewjah Tkalif Di — Phir Karma Ne Hisaab Liya",
        "category": "karma_stories",
        "format": "short",
        "hook": "He caused pain for no reason. Years later, karma came — and it remembered everything.",
        "hook_hindi": "Usne bewajah dukh diya. Saalon baad karma aaya — aur usne sab yaad rakha tha.",
        "core_conflict": "A cruel and selfish person causes suffering to many. Life slowly reverses their fortunes.",
        "twist": "Karma arrives through the very person they hurt most — who had risen above their circumstances.",
        "moral": "What you give comes back — always.",
        "moral_hindi": "जो देते हो वो लौटकर आता है — हमेशा।",
        "angle": "Karma Justice",
        "topic": "karma story hindi badla justice",
        "audience_hook": "Karma dekha hai kabhi apni life mein? Comment mein share karo!",
    },
    {
        "title": "Zindagi Ne Ek Baar Mouka Diya — Usne Chhodd Diya",
        "category": "karma_stories",
        "format": "long",
        "hook": "Life gave him one chance. He threw it away. And then life remembered.",
        "hook_hindi": "Zindagi ne ek mauka diya. Usne chodh diya. Aur phir zindagi ne yaad rakha.",
        "core_conflict": "A person betrays a golden opportunity and the trust of others for short-term gain.",
        "twist": "Years later, the person they betrayed becomes the only one who can help them — and chooses to.",
        "moral": "Forgiveness is the highest form of karma.",
        "moral_hindi": "माफ़ी कर्म का सबसे बड़ा रूप है।",
        "angle": "Redemption Karma",
        "topic": "karma story hindi redemption moral",
        "audience_hook": "Aapne kabhi kisi ko maaf kiya jo deserve nahi karta tha? Comment karo!",
    },
    {
        "title": "Woh Paisa Jo Bura Tha — Wapas Gaya Bura Hokar",
        "category": "karma_stories",
        "format": "short",
        "hook": "Money earned the wrong way — it always returns the same way it was taken.",
        "hook_hindi": "Galat tarike se kamaya paisa — hamesha galat tarike se hi wapas jaata hai.",
        "core_conflict": "A person accumulates wealth through dishonest means and watches it slip away in equally painful ways.",
        "twist": "The final loss isn't money — it's the relationship that money could never buy.",
        "moral": "Ill-gotten gains carry a hidden interest rate.",
        "moral_hindi": "बेईमानी की कमाई पर एक छुपा ब्याज़ लगा होता है।",
        "angle": "Money Karma",
        "topic": "karma story hindi money greed",
        "audience_hook": "Yeh sach mein hota hai? Comment mein batao!",
    },
    {
        "title": "Ek Ache Kaam Ka Badla — 10 Saal Baad",
        "category": "karma_stories",
        "format": "long",
        "hook": "He did one good deed 10 years ago and forgot about it. It came back with interest.",
        "hook_hindi": "Usne 10 saal pehle ek nek kaam kiya aur bhool gaya. Woh wapas aaya — fayde ke saath.",
        "core_conflict": "A small act of kindness done long ago ripples forward in time and returns to save the giver.",
        "twist": "The person saved by the old kindness is the one who prevents a devastating loss years later.",
        "moral": "A good deed is a seed — its harvest comes when you need it most.",
        "moral_hindi": "एक नेक काम एक बीज है — इसकी फसल तब आती है जब सबसे ज़्यादा ज़रूरत हो।",
        "angle": "Good Karma Story",
        "topic": "karma story hindi good deed reward",
        "audience_hook": "Tumhara koi nek kaam ka badla mila hai? Comment mein zaroor batao!",
    },

    # ─── REAL LIFE FACTS ──────────────────────────────────────────────────────

    {
        "title": "Ek Aam Aadmi Ki Kahani Jo Duniya Badal Gayi",
        "category": "real_life_facts",
        "format": "long",
        "hook": "He was nobody. Then one decision changed the world forever.",
        "hook_hindi": "Woh koi nahi tha. Phir ek faisle ne duniya ko hamesha ke liye badal diya.",
        "core_conflict": "The true story of an ordinary person whose single courageous decision created massive change.",
        "twist": "They never sought fame or recognition — and that's exactly why the change lasted.",
        "moral": "Ordinary people make extraordinary history.",
        "moral_hindi": "साधारण लोग असाधारण इतिहास बनाते हैं।",
        "angle": "Inspiring Real Story",
        "topic": "real life inspiring story hindi change maker",
        "audience_hook": "Aisa karo kuch bhi chota jo duniya ko better banaye — share karo!",
    },
    {
        "title": "Sach Mein Hua Tha Yeh — Believe It Or Not",
        "category": "real_life_facts",
        "format": "short",
        "hook": "This really happened. And it's more unbelievable than any fiction.",
        "hook_hindi": "Yeh sach mein hua tha. Kisi bhi kalpana se zyada ajib.",
        "core_conflict": "A series of real-life events so extraordinary they sound fictional — with verified sources.",
        "twist": "The most unbelievable part is the simplest explanation at the core.",
        "moral": "Reality is the greatest storyteller.",
        "moral_hindi": "हकीकत सबसे बड़ी कहानीकार है।",
        "angle": "True Story Facts",
        "topic": "real life facts hindi unbelievable true story",
        "audience_hook": "Yeh sach hai — believe it or not? Comment mein batao!",
    },
    {
        "title": "Woh Bachcha Jo Doctor, Engineer, Aur Lawyer Tha — Ek Saath",
        "category": "real_life_facts",
        "format": "short",
        "hook": "He held 3 professional degrees before he was 21. And nobody knew his real secret.",
        "hook_hindi": "Uske paas 21 saal ki umra mein 3 professional degrees theen. Aur uska asli raaz kisi ko pata nahi tha.",
        "core_conflict": "The true story of a child prodigy whose extraordinary achievements hid a painful personal struggle.",
        "twist": "His academic success was a coping mechanism for a trauma his family never acknowledged.",
        "moral": "Success and happiness are not the same thing.",
        "moral_hindi": "सफलता और खुशी एक चीज़ नहीं होती।",
        "angle": "Real Life Prodigy",
        "topic": "real life story hindi prodigy child success",
        "audience_hook": "Success ke peeche struggle ka andaza hota hai? Comment karo!",
    },

    # ─── MORAL STORIES ────────────────────────────────────────────────────────

    {
        "title": "Zindagi Ka Sabse Keemti Waqt — Aur Hum Usse Barbaad Kar Rahe Hain",
        "category": "moral_stories",
        "format": "long",
        "hook": "We are spending the most valuable currency we have — and we don't even notice.",
        "hook_hindi": "Hum apni sabse keemti cheez kharch kar rahe hain — aur hum notice bhi nahi kar rahe.",
        "core_conflict": "A story illustrating how we unknowingly waste time on things that don't matter.",
        "twist": "The moment the protagonist understands time's value comes too late — but just early enough.",
        "moral": "Time is the only currency that cannot be earned back.",
        "moral_hindi": "वक्त एकमात्र ऐसी मुद्रा है जो वापस नहीं कमाई जा सकती।",
        "angle": "Time Value Moral",
        "topic": "moral story hindi time value life lesson",
        "audience_hook": "Kya tum apna time wisely use kar rahe ho? Comment mein honestly batao!",
    },
    {
        "title": "Ek Beizzati Ne Zindagi Badal Di",
        "category": "moral_stories",
        "format": "short",
        "hook": "The humiliation that broke him became the fuel that built him.",
        "hook_hindi": "Jis beizzati ne use toda — wahi bana di uski zindagi.",
        "core_conflict": "A person publicly humiliated uses that pain as the driving force for extraordinary growth.",
        "twist": "When they reach success, they use their platform not for revenge but to prevent others from facing the same.",
        "moral": "Pain is only wasted when it doesn't teach you something.",
        "moral_hindi": "दर्द तभी बेकार होता है जब वो कुछ नहीं सिखाता।",
        "angle": "Redemption Moral",
        "topic": "moral story hindi humiliation growth",
        "audience_hook": "Beizzati se kuch sikha hai kabhi? Comment mein share karo!",
    },
    {
        "title": "Rishta — Paisa Nahi, Samay Chahiye",
        "category": "moral_stories",
        "format": "long",
        "hook": "He gave his family everything money could buy. He never gave them what they really needed.",
        "hook_hindi": "Usne apne ghar walo ko paise se khareedne wali har cheez di. Jo chahiye tha woh kabhi nahi diya.",
        "core_conflict": "A successful person believes providing financially is enough — and discovers too late what their family truly needed.",
        "twist": "A simple conversation that was avoided for years could have saved everything.",
        "moral": "Presence is the gift no money can replace.",
        "moral_hindi": "साथ देना वो तोहफा है जिसे पैसे नहीं खरीद सकते।",
        "angle": "Family Moral Story",
        "topic": "moral story hindi family relationship money",
        "audience_hook": "Apne ghar walo ko samay de rahe ho? Comment mein honest reply karo!",
    },
    {
        "title": "Woh Insaan Jo Khud Ko Kabhi Important Nahi Samajhta Tha",
        "category": "moral_stories",
        "format": "short",
        "hook": "He thought he didn't matter. Then the world showed him just how wrong he was.",
        "hook_hindi": "Woh samajhta tha ki woh matter nahi karta. Phir duniya ne bataya ki woh kitna galat tha.",
        "core_conflict": "A person who undervalues themselves discovers through a crisis how many people their existence has quietly sustained.",
        "twist": "The very qualities they hated about themselves were the ones that made them irreplaceable to others.",
        "moral": "You matter more than you know.",
        "moral_hindi": "आप जितना सोचते हैं उससे कहीं ज़्यादा मायने रखते हैं।",
        "angle": "Self-Worth Moral",
        "topic": "moral story hindi self worth value important",
        "audience_hook": "Kabhi aisa feel hua ki aap matter nahi karte? Comment mein batao!",
    },
    {
        "title": "Daulat Aur Sukoon — Ek Saath Nahi Milte?",
        "category": "moral_stories",
        "format": "long",
        "hook": "He had everything. He had nothing.",
        "hook_hindi": "Uske paas sab kuch tha. Phir bhi kuch nahi tha.",
        "core_conflict": "A wealthy man discovers at the peak of his success that the pursuit of wealth has left him completely empty.",
        "twist": "The source of peace he seeks was always in the people he sacrificed on the way up.",
        "moral": "Wealth without peace is poverty of the soul.",
        "moral_hindi": "बिना शांति के दौलत आत्मा की गरीबी है।",
        "angle": "Wealth vs Peace Moral",
        "topic": "moral story hindi wealth happiness life",
        "audience_hook": "Daulat ya sukoon — kya choose karoge? Comment mein batao!",
    },

    # ─── More across categories for variety ───────────────────────────────────

    {
        "title": "Sabse Bada Dushman — Khud Ki Soch",
        "category": "psychological",
        "format": "short",
        "hook": "Your worst enemy lives inside your head. And it sounds exactly like you.",
        "hook_hindi": "Tumhara sabse bada dushman tumhare dimag mein rehta hai — aur woh bilkul tumhari tarah bolta hai.",
        "core_conflict": "A person's negative self-talk manifests as a psychological barrier that destroys every opportunity.",
        "twist": "The voice they've been fighting was planted by a single traumatic moment they've never addressed.",
        "moral": "The battles in your mind determine every battle in your life.",
        "moral_hindi": "मन की लड़ाइयाँ ही ज़िंदगी की हर लड़ाई तय करती हैं।",
        "angle": "Inner Voice Psychological",
        "topic": "psychological story hindi negative thinking mindset",
        "audience_hook": "Khud ki soch ne kabhi rokha hai? Comment mein honestly batao!",
    },
    {
        "title": "Woh Baat Jo Marne Ke Baad Pata Chali",
        "category": "mystery_stories",
        "format": "long",
        "hook": "He passed away. And then they found something that changed everything they knew about him.",
        "hook_hindi": "Woh chale gaye. Aur phir jo mila — usne unke baare mein poori soch badal di.",
        "core_conflict": "After a person's death, their family discovers evidence of a secret life that completely redefines who they were.",
        "twist": "The secret life was one of anonymous good — they had been quietly helping hundreds of people.",
        "moral": "True goodness doesn't need recognition.",
        "moral_hindi": "असली भलाई को पहचान की ज़रूरत नहीं होती।",
        "angle": "Post-Death Mystery Reveal",
        "topic": "mystery story hindi secret good person",
        "audience_hook": "Aisa koi hai tumhari life mein? Comment mein share karo!",
    },
    {
        "title": "Ek Teacher Jisko Sab Bhool Gaye — Par Usne Sab Badal Diya",
        "category": "real_life_facts",
        "format": "long",
        "hook": "Nobody remembered her name. But they all became who they are because of her.",
        "hook_hindi": "Kisi ko uska naam yaad nahi raha. Par jo woh ban gaye — woh usi ki wajah se the.",
        "core_conflict": "The untold story of an ordinary teacher whose impact spans generations without recognition.",
        "twist": "The day before retirement, a student reveals how she changed their entire life — and it turns out she did the same for thousands.",
        "moral": "The most powerful people are often the least celebrated.",
        "moral_hindi": "सबसे ताकतवर लोग अक्सर सबसे कम सराहे जाते हैं।",
        "angle": "Teacher Real Story",
        "topic": "real life story hindi teacher impact inspiring",
        "audience_hook": "Apne favorite teacher ko tag karo jo aapki life mein farq laye!",
    },
    {
        "title": "Shuruaat Koi Bhi Ho — Ant Tumhara Hoga",
        "category": "moral_stories",
        "format": "short",
        "hook": "Where you start means nothing. Where you finish is everything.",
        "hook_hindi": "Shuruaat koi bhi ho — sirf yahi hai ki tum kahan khatam hote ho.",
        "core_conflict": "A person from the worst possible starting point defies every expectation through relentless determination.",
        "twist": "Their greatest strength came directly from their hardest disadvantage.",
        "moral": "Your beginning doesn't determine your end.",
        "moral_hindi": "शुरुआत तुम्हारा अंत तय नहीं करती।",
        "angle": "Motivational Moral",
        "topic": "moral story hindi success from nothing motivation",
        "audience_hook": "Kahaan se shuru kiya tha tumne? Comment mein batao!",
    },
    {
        "title": "Crime Ka Woh Pattern Jo Police Ne 5 Saal Baad Dekha",
        "category": "crime_stories",
        "format": "long",
        "hook": "The crimes seemed unconnected. Until one analyst found the pattern.",
        "hook_hindi": "Woh crimes alag-alag lagte the. Jab tak ek analyst ne pattern nahi dekha.",
        "core_conflict": "A series of seemingly unrelated crimes across different cities revealed to be connected by a hidden pattern.",
        "twist": "The connection runs far deeper than anyone imagined — and reaches into the investigation itself.",
        "moral": "Truth hides in patterns most people aren't looking for.",
        "moral_hindi": "सच्चाई उन पैटर्न में छुपी होती है जिन्हें ज़्यादातर लोग नहीं देखते।",
        "angle": "Crime Investigation",
        "topic": "crime story hindi police investigation pattern",
        "audience_hook": "Crime shows dekhte ho? Share karo ek crime fan ke saath!",
    },
]
