from __future__ import annotations


VIRAL_TOPIC_BANK: list[dict[str, str]] = [
    {"title": "What Happens to Your Body After 30 Days of Pushups", "angle": "Body Transformation", "topic": "30 days pushups result", "audience_value": "Explain exact biological and aesthetic changes from daily pushups"},
    {"title": "30 Din Tak Roz Squats Karne Se Kya Hota Hai?", "angle": "Body Transformation", "topic": "30 days squats result", "audience_value": "Break down leg muscle growth and core stability from daily squats"},
    {"title": "What Happens If You Walk 10,000 Steps for 30 Days", "angle": "Fat Loss", "topic": "30 days walking result", "audience_value": "Highlight the hidden fat loss and mental clarity benefits of daily walking"},
    {"title": "30 Din Plank Karne Ka Asli Result", "angle": "Core Strength", "topic": "30 days plank challenge", "audience_value": "Show how planks fix posture and build deep core strength over a month"},
    {"title": "If You Stop Eating Sugar for 14 Days", "angle": "Diet & Health", "topic": "quit sugar benefits", "audience_value": "Share exact energy and fat loss results of cutting sugar"},
    {"title": "Dieting Ke Baad Bhi Belly Fat Kyun Nahi Jata", "angle": "Fat Loss", "topic": "belly fat plateau", "audience_value": "Understand the hidden reason fat loss stalls"},
    {"title": "Raat Ke Khane Ke Baad Chalne Se Kya Hota Hai", "angle": "Fat Loss", "topic": "post dinner walk", "audience_value": "Use a simple habit to improve digestion and fat loss"},
    {"title": "Workout Excuses Khatam Karne Ka 10 Minute Rule", "angle": "Motivation", "topic": "workout excuses", "audience_value": "Make it easier to start training on low-motivation days"},
    {"title": "Tumhare Pushups Se Chest Kyun Nahi Ban Rahi?", "angle": "Form Fix", "topic": "pushup mistakes", "audience_value": "Fix form mistakes that kill chest growth"},
    {"title": "Fat Loss Ke Liye Jogging Sahi Hai Ya Sprinting?", "angle": "Comparison", "topic": "running for fat loss", "audience_value": "Choose the cardio style that fits your goal"},
    {"title": "Squats Ki Ye Mistake Tumhare Ghutne Kharab Kar Rahi Hai", "angle": "Form Fix", "topic": "squat knee pain", "audience_value": "Protect your knees while building stronger legs"},
    {"title": "Wednesday Tak Gym Ki Motivation Kyun Khatam Hoti Hai?", "angle": "Mindset", "topic": "motivation crash", "audience_value": "Build a system that survives mood swings"},
    {"title": "Morning Mobility Tumhara Poora Din Badal Sakti Hai", "angle": "Mobility", "topic": "morning mobility routine", "audience_value": "Feel looser and more energetic before work"},
    {"title": "Asli Wajah Kyun 90% Log Gym Chod Dete Hain", "angle": "Psychology", "topic": "why beginners quit gym", "audience_value": "Stay consistent longer than the average beginner"},
    {"title": "Ye Breathing Trick Workout Workout Anxiety Kam Karti Hai", "angle": "Recovery", "topic": "breathing for calm focus", "audience_value": "Use breath to calm the mind before training"},
    {"title": "Fasted Cardio Sahi Hai Ya Phir Ek Bada Myth?", "angle": "Truth Bomb", "topic": "fasted cardio", "audience_value": "Avoid a fat-loss strategy that backfires for many people"},
    {"title": "Wo Ek Habit Jo Discipline Ko Aasan Banati Hai", "angle": "Motivation", "topic": "discipline habit", "audience_value": "Turn discipline into a repeatable daily action"},
    {"title": "Pushup Seekhne Ka Sabse Aasan Tarika Beginners Ke Liye", "angle": "Beginner Guide", "topic": "beginner pushup progression", "audience_value": "Start building upper-body strength without feeling stuck"},
    {"title": "Pullups Sirf Back Hi Nahi Kafi Kuch Banate Hain", "angle": "Strength", "topic": "pullup benefits", "audience_value": "Understand why pullups improve strength and confidence"},
    {"title": "Running Habit Jis Se Joints Safe Rahte Hain", "angle": "Recovery", "topic": "safe running habit", "audience_value": "Run more consistently with less soreness"},
    {"title": "Tum Lazy Nahi Ho, Sirf Overstimulated Ho", "angle": "Mindset", "topic": "overstimulation and laziness", "audience_value": "Break the scroll-fatigue cycle and start moving again"},
    {"title": "Bade Shoulders Ke Liye Sahi Pressing Form", "angle": "Form Fix", "topic": "shoulder press form", "audience_value": "Train shoulders better with safer mechanics"},
    {"title": "Yoga Fat Loss Mein Kaise Madad Karta Hai?", "angle": "Yoga Benefits", "topic": "yoga for fat loss", "audience_value": "See how stress control and consistency support fat loss"},
    {"title": "Leg Press Ki Wo Trick Jo Sab Badal Dega", "angle": "Form Fix", "topic": "leg press cue", "audience_value": "Get more leg drive without lower-back compensation"},
    {"title": "Jumping Jacks Aaj Bhi Kyun Kaam Karte Hain?", "angle": "Cardio", "topic": "jumping jacks workout", "audience_value": "Use a classic movement for fast full-body activation"},
    {"title": "Aalas Door Karne Ka 30 Second Rule", "angle": "Motivation", "topic": "procrastination reset", "audience_value": "Start hard tasks before your brain talks you out of them"},
    {"title": "Running Ko Ek Hafte Mein Aasan Kaise Banayein?", "angle": "Beginner Guide", "topic": "running stamina", "audience_value": "Improve breathing and pacing without overtraining"},
    {"title": "Muscle Dard Ka Matlab Ye Nahi Ki Growth Ho Rahi Hai", "angle": "Truth Bomb", "topic": "muscle soreness myths", "audience_value": "Judge progress by better signals than pain"},
    {"title": "Roz Pushups Karne Se Kya Confidence Aata Hai?", "angle": "Habit", "topic": "daily pushup habit", "audience_value": "Use one simple challenge to build discipline"},
    {"title": "Desk Job Ki Thakan Door Karne Ka Yoga Pose", "angle": "Yoga Relief", "topic": "desk stiffness yoga", "audience_value": "Release tightness from long sitting"},
    {"title": "Beginners Ko Workout Feeling Se Nahi, Reps Se Track Karna Chahiye", "angle": "Beginner Mindset", "topic": "tracking reps", "audience_value": "Measure progress more honestly from week to week"},
    {"title": "Jinko Cardio Pasand Nahi, Unke Liye Best Option", "angle": "Relatable", "topic": "easy cardio ideas", "audience_value": "Find a sustainable cardio option you can actually repeat"},
    {"title": "Roz 8,000 Kadam Chalne Ke Asli Fayde", "angle": "Health", "topic": "daily steps habit", "audience_value": "Understand why walking still wins for many people"},
    {"title": "Bicep Curl Ki Mistake Jo Arms Grow Nahi Hone Deti", "angle": "Form Fix", "topic": "bicep curl mistake", "audience_value": "Train biceps with better tension and control"},
    {"title": "Tumhari Raat Ki Aadat Subah Ka Workout Decide Karti Hai", "angle": "Routine", "topic": "night routine for workouts", "audience_value": "Make morning training easier before you wake up"},
    {"title": "Ye Ek Mindset Fat Loss Ko Asan Bana Dega", "angle": "Psychology", "topic": "sustainable fat loss mindset", "audience_value": "Stop relying on temporary motivation spikes"},
    {"title": "Jaldi Thakne Walo Ke Liye Running Form Fix", "angle": "Form Fix", "topic": "running form for beginners", "audience_value": "Save energy and improve pace with better mechanics"},
    {"title": "Pullup Seekhne Ka Wo Step Jo Sab Skip Karte Hain", "angle": "Strength", "topic": "pullup progression", "audience_value": "Build toward your first pullup with less frustration"},
    {"title": "Sone Se Pehle Yoga Karne Se Recovery Kyun Bढ़ti Hai?", "angle": "Recovery", "topic": "sleep yoga", "audience_value": "Relax the body and recover better overnight"},
    {"title": "Stress Aane Par Khane Ki Aadat Kaise Rokein?", "angle": "Mindset", "topic": "stress eating", "audience_value": "Interrupt emotional eating before it starts"},
    {"title": "Heavy Squats Mein Sahi Saans Lena Kyun Zaroori Hai?", "angle": "Strength", "topic": "squat bracing", "audience_value": "Feel stronger and safer under the weight"},
    {"title": "Workout Se Pehle Jumping Jacks: Sahi Ya Galat?", "angle": "Comparison", "topic": "jumping jacks warmup", "audience_value": "Decide if they belong in your warmup routine"},
    {"title": "Sirf 20 Minute Daudne Ka Asli Fayda", "angle": "Health", "topic": "20 minute run benefits", "audience_value": "Use short runs for mood, stamina, and fat loss"},
    {"title": "Tum Baar Baar Workout Kyun Shuru Aur Khatam Karte Ho?", "angle": "Psychology", "topic": "restart cycle", "audience_value": "Break the all-or-nothing pattern that kills progress"},
    {"title": "Cobra Pose Karne Ka Ye Tarika Ekdum Sahi Hai", "angle": "Yoga Form", "topic": "cobra pose cue", "audience_value": "Make one yoga pose safer and more effective"},
    {"title": "Asli Taaqat Ke Liye Pushups Ya Bench Press?", "angle": "Comparison", "topic": "pushups vs bench press", "audience_value": "Pick the movement that matches your current goal"},
    {"title": "Kya Sach Mein Sirf Pet Ki Charbi Kam Ho Sakti Hai?", "angle": "Myth Busting", "topic": "spot reduction myth", "audience_value": "Stop wasting effort on a myth that keeps spreading"},
    {"title": "Workout Ko Apni Aadat Kaise Banayein?", "angle": "Habit", "topic": "repeatable workout routine", "audience_value": "Build a fitness plan you can sustain in real life"},
    {"title": "Squats Karte Waqt Tumhari Tange Kyun Kampti Hain?", "angle": "Explainer", "topic": "legs shaking in squats", "audience_value": "Understand whether it is weakness, fatigue, or form"},
    {"title": "Running Ki Ye Trick Tumhara Posture Sahi Kar Degi", "angle": "Form Fix", "topic": "running posture", "audience_value": "Move better while reducing upper-body tension"},
    {"title": "Wo Mindset Jo Dard Ko Result Mein Badal Deta Hai", "angle": "Motivation", "topic": "pain into progress mindset", "audience_value": "Use discomfort as feedback instead of quitting"},
    {"title": "Yoga Kaise Tumhare Andar Discipline Build Karta Hai", "angle": "Yoga Motivation", "topic": "discipline through yoga", "audience_value": "See how calm routines still build a strong identity"},
    {"title": "Galat Warmup Ko Sahi Karne Ka Sabse Tezz Tarika", "angle": "Workout Prep", "topic": "warmup mistakes", "audience_value": "Start sessions feeling ready instead of stiff"},
    {"title": "Shuru Mein Pullups Karna Kyun Namumkin Lagta Hai?", "angle": "Beginner Guide", "topic": "first pullup struggle", "audience_value": "Understand the missing strength pieces and fix them"},
    {"title": "Bicep Curl Ki Wo Speed Jis Se Muscle Banegi", "angle": "Form Fix", "topic": "bicep curl tempo", "audience_value": "Grow your arms with better control not just heavier reps"},
    {"title": "Lagatar 7 Din Subah Chalne Se Body Me Kya Hoga?", "angle": "Habit", "topic": "7 day walking challenge", "audience_value": "Build momentum with a low-friction fitness reset"},
    {"title": "Acchi Neend Fat Loss Ka Sabse Bada Raj Kyun Hai?", "angle": "Health", "topic": "sleep and fat loss", "audience_value": "See how recovery affects cravings and effort"},
    {"title": "Jab Fitness Ka Man Na Kare Toh Ye Workout Karo", "angle": "Relatable", "topic": "low motivation workout", "audience_value": "Keep your streak alive with a lower-bar session"},
    {"title": "Leg Press Ki Wo Galti Jo Tumhari Mehnat Kharab Karti Hai", "angle": "Form Fix", "topic": "leg press foot placement", "audience_value": "Hit quads better with smarter setup"},
    {"title": "Mental Peace Ke Liye Running Kaise Karein?", "angle": "Mindset", "topic": "running for mental health", "audience_value": "Turn cardio into a focus and mood ritual"},
    {"title": "Busy Logo Ke Liye Sabse Aasan Yoga Routine", "angle": "Lifestyle", "topic": "busy people yoga", "audience_value": "Make calm and mobility fit into a packed day"},
    {"title": "Shoulders Mein Dard Hota Hai Par Size Kyun Nahi Badhta?", "angle": "Form Fix", "topic": "shoulders not growing", "audience_value": "Separate real tension from useless fatigue"},
    {"title": "Workout Motivation Videos Ka Kadwa Sach", "angle": "Contrarian", "topic": "motivation videos", "audience_value": "Learn why systems matter more than hype"},
    {"title": "Ye Pushup Variation Tumhari Asli Taaqat Mapegi", "angle": "Workout Tip", "topic": "pushup variation", "audience_value": "Choose a smarter variation for your level"},
    {"title": "Running Ka Pehla Kilometer Kaisa Feel Hona Chahiye?", "angle": "Running", "topic": "first kilometer pacing", "audience_value": "Stop starting runs too fast and crashing early"},
    {"title": "Diet Ko Asan Banane Ki Discipline Trick", "angle": "Diet Psychology", "topic": "diet discipline trick", "audience_value": "Reduce decision fatigue around food"},
    {"title": "Sirf Stretching Karne Ka Matlab Mobility Nahi Hai", "angle": "Mobility", "topic": "stretching vs mobility", "audience_value": "Train movement quality with more intention"},
    {"title": "Pullup Mein Lat Muscles Kaise Feel Karein?", "angle": "Form Fix", "topic": "pullup lat activation", "audience_value": "Improve pulling strength with better connection"},
    {"title": "Monday Ka Workout Miss Karne Ki Aadat Kaise Chodein", "angle": "Routine", "topic": "monday workout consistency", "audience_value": "Build a system that starts the week strong"},
    {"title": "Rest Day Par Choti Si Run Lene Ke Fayde", "angle": "Recovery", "topic": "easy recovery runs", "audience_value": "Move on off days without draining yourself"},
    {"title": "Cobra Pose Asaan Dikhta Hai Par Hai Kyun Nahi", "angle": "Yoga Insight", "topic": "cobra pose difficulty", "audience_value": "Understand the body awareness behind simple poses"},
    {"title": "Muscle Banane Ka Wo Rule Jo Beginners Skip Karte Hain", "angle": "Strength", "topic": "beginner muscle building rule", "audience_value": "Grow faster by respecting basics early"},
    {"title": "Tezi Se Fat Burn Ke Liye Jumping Jacks Ya Running?", "angle": "Comparison", "topic": "jumping jacks vs running", "audience_value": "Choose the better tool for your time and energy"},
    {"title": "Tumhara Fitness Plan 3 Din Baad Kyun Fail Hota Hai?", "angle": "Psychology", "topic": "3 day fitness drop", "audience_value": "Fix the planning mistake that causes quick burnout"},
    {"title": "Biceps Workout Ki Ye Habit Tumhare Elbows Ko Bachayegi", "angle": "Form Fix", "topic": "bicep elbow pain", "audience_value": "Keep arm training effective and joint-friendly"},
    {"title": "The Best 8 Second Habit to Start Running", "angle": "Beginner Guide", "topic": "starting running habit", "audience_value": "Make cardio feel less overwhelming on day one"},
    {"title": "Why Yoga Works for Angry Tired Minds", "angle": "Recovery", "topic": "yoga for stress and anger", "audience_value": "Calm the nervous system without checking out"},
    {"title": "The Squat Depth Truth Nobody Explains Well", "angle": "Myth Busting", "topic": "squat depth", "audience_value": "Understand depth based on your body not social media"},
    {"title": "Pushups Every Day Good or Bad", "angle": "Comparison", "topic": "daily pushups", "audience_value": "Know when daily practice helps and when it hurts"},
    {"title": "How Running Builds Discipline Outside the Gym", "angle": "Mindset", "topic": "running and discipline", "audience_value": "Use cardio as mental training not just calorie burn"},
    {"title": "The Posture Cue That Improves Shoulder Press", "angle": "Form Fix", "topic": "shoulder press posture", "audience_value": "Press stronger with less neck strain"},
    {"title": "Why Tiny Workouts Beat Huge Plans", "angle": "Motivation", "topic": "small workouts", "audience_value": "Build momentum with actions you can actually finish"},
    {"title": "This Leg Day Mistake Makes You Fear Squats", "angle": "Psychology", "topic": "leg day fear", "audience_value": "Train legs with better confidence and pacing"},
    {"title": "The Simple Yoga Routine for Stiff Hips", "angle": "Yoga Relief", "topic": "yoga for stiff hips", "audience_value": "Move with less tightness and better posture"},
    {"title": "Why Pullups Teach Patience Better Than Motivation", "angle": "Mindset", "topic": "pullup patience", "audience_value": "Stay committed through slow visible progress"},
    {"title": "This Running Mistake Makes Cardio Feel Miserable", "angle": "Form Fix", "topic": "running too hard", "audience_value": "Enjoy cardio more by pacing correctly"},
    {"title": "What to Do When You Miss 3 Workouts", "angle": "Recovery Mindset", "topic": "getting back after missed workouts", "audience_value": "Restart fast without guilt or self-sabotage"},
    {"title": "The Bicep Secret Is Not Heavier Weights", "angle": "Truth Bomb", "topic": "bicep tension", "audience_value": "Grow arms with tension and control first"},
    {"title": "Why Jumping Jacks Wake Up the Whole Body", "angle": "Workout Prep", "topic": "jumping jacks benefits", "audience_value": "Use a fast movement to raise energy quickly"},
    {"title": "How Yoga Helps You Show Up More Calmly", "angle": "Lifestyle", "topic": "yoga and calm confidence", "audience_value": "Build emotional steadiness through simple practice"},
    {"title": "The Pushup Breathing Cue You Need", "angle": "Form Fix", "topic": "pushup breathing", "audience_value": "Create more control and full-body tension"},
    {"title": "Why Running Slow Can Make You Faster", "angle": "Running", "topic": "easy pace running", "audience_value": "Train stamina smarter instead of harder"},
    {"title": "The Best Home Workout When Space Is Tight", "angle": "Quick Workout", "topic": "small space workout", "audience_value": "Train at home with almost no setup"},
    {"title": "What Discipline Looks Like on Bad Days", "angle": "Motivation", "topic": "discipline on bad days", "audience_value": "Redefine success when energy is low"},
    {"title": "This Shoulder Press Change Saves Your Lower Back", "angle": "Form Fix", "topic": "shoulder press lower back", "audience_value": "Press overhead with better core control"},
    {"title": "Why Yoga Is a Strength Practice Too", "angle": "Yoga Strength", "topic": "yoga as strength work", "audience_value": "See how controlled positions build real strength"},
    {"title": "The Leg Press Setup for Safer Reps", "angle": "Workout Tip", "topic": "safe leg press setup", "audience_value": "Protect knees and back while training hard"},
    {"title": "How to Make Running Part of Your Identity", "angle": "Mindset", "topic": "running identity", "audience_value": "Stay consistent by changing self-image not just goals"},
    {"title": "The Pullup Cue That Stops Swinging", "angle": "Form Fix", "topic": "pullup swinging", "audience_value": "Improve cleaner reps and real back work"},
    {"title": "Why Most Fat Loss Advice Fails Busy People", "angle": "Lifestyle", "topic": "fat loss for busy people", "audience_value": "Use realistic habits instead of perfect plans"},
    {"title": "This Squat Cue Helps You Feel Stronger Fast", "angle": "Strength", "topic": "squat confidence cue", "audience_value": "Use one simple cue for better leg drive"},
    {"title": "The Yoga Reset You Need After a Long Day", "angle": "Recovery", "topic": "after work yoga", "audience_value": "Release stress and stiffness in minutes"},
    {"title": "What Happens When You Stop Negotiating With Yourself", "angle": "Motivation", "topic": "self negotiation", "audience_value": "Build a mindset that respects promises to yourself"},
    {"title": "Why Running Is Better Than Waiting for Motivation", "angle": "Mindset", "topic": "running and motivation", "audience_value": "Use action to create energy instead of waiting for it"},
    {"title": "The Beginner Fitness Trap Called All or Nothing", "angle": "Psychology", "topic": "all or nothing fitness", "audience_value": "Stay in the game longer with a balanced approach"},
]


def filter_viral_topics(theme: str | None = None) -> list[dict[str, str]]:
    if not theme:
        return VIRAL_TOPIC_BANK.copy()
    terms = [part.strip().lower() for part in theme.split() if part.strip()]
    if not terms:
        return VIRAL_TOPIC_BANK.copy()
    filtered = [
        topic
        for topic in VIRAL_TOPIC_BANK
        if any(term in " ".join(topic.values()).lower() for term in terms)
    ]
    unmatched = [t for t in VIRAL_TOPIC_BANK if t not in filtered]
    return filtered + unmatched


def sample_topic_titles(items: list[dict[str, str]], limit: int = 18) -> list[str]:
    return [item["title"] for item in items[:limit]]
